import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service — SmartSarmaya",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-full flex-col bg-slate-50">
      <Navbar />
      <main className="mx-auto max-w-3xl flex-1 px-4 py-12 sm:px-6">
        <h1 className="text-3xl font-bold text-navy-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: July 2026</p>

        <div className="prose prose-slate mt-8 space-y-6 text-slate-700">
          <section>
            <h2 className="text-xl font-semibold text-navy-900">Acceptance of Terms</h2>
            <p>
              By using SmartSarmaya, you agree to these Terms of Service. If you do not
              agree, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-navy-900">Not Financial Advice</h2>
            <p>
              All content generated by SmartSarmaya, including portfolio analysis and
              stock picks, is produced by artificial intelligence for informational
              and educational purposes only. It does not constitute financial,
              investment, tax, or legal advice. Always consult a licensed financial
              advisor before making investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-navy-900">AI Limitations</h2>
            <p>
              AI-generated reports may contain errors or outdated information. Market
              data is sourced from third-party providers and may not be real-time or
              accurate. You use this service at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-navy-900">Shariah Compliance</h2>
            <p>
              Any references to Shariah-compliant picks are AI investment suggestions
              only and should not be interpreted as religious rulings or fatwas.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-navy-900">Limitation of Liability</h2>
            <p>
              SmartSarmaya and its operators shall not be liable for any losses or
              damages arising from the use of this service or reliance on its
              outputs.
            </p>
          </section>
        </div>

        <Link
          href="/"
          className="mt-10 inline-block text-emerald-600 transition hover:text-emerald-700"
        >
          &larr; Back to Home
        </Link>
      </main>
      <Footer />
    </div>
  );
}
